development:
 adapter:  postgresql
 encoding: utf-8
 database: local-event-app
 username: postgres
 password: postgres
 host: localhost
 port: 5432

test:
 adapter:  postgresql
 encoding: utf-8
 database: local-event-app-test
 username: postgres
 password: postgres
 host: localhost
 port: 5432
 
